version: '3.8'

services:
  mongodb:
    image: mongo:5
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGODB_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGODB_PASSWORD
      MONGO_INITDB_DATABASE: human-assistant
    ports:
      - '27017:27017'

  mongodb-seed:
    image: mongo:5
    container_name: mongodb-seed
    depends_on:
      - mongodb
    volumes:
      - ./mongodb-init:/mongodb-init
    links:
      - mongodb
    
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - '6379:6379'